services:
  mariadb:
    image: mariadb:10.11
    container_name: tallerjava-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: mariapass
      MARIADB_DATABASE: tallerJava
      MARIADB_USER: taller
      MARIADB_PASSWORD: taller123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmariapass"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
  influxdb:
    image: influxdb:1.8
    container_name: tallerjava-influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: metricasTallerJava
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: tallerjava-grafana
    ports:
      - "3003:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  ollama:
    image: ollama/ollama:latest
    container_name: tallerjava-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  wildfly:
    build: .
    container_name: tallerjava-wildfly
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_DB: tallerJava
      MARIADB_USER: root
      MARIADB_PASSWORD: mariapass
      
      INFLUX_URL: http://influxdb:8086
      INFLUX_DB: metricasTallerJava
    depends_on:
      mariadb:
        condition: service_healthy
      influxdb:
        condition: service_started
volumes:
  mariadb_data:
  influxdb_data:
  grafana_data:
  ollama_data:
